---
- name: "[NC-Rescue] - Remove the new Instance."
  file: path="{{ nextcloud_webroot }}" state=absent

- name: "[NC-Rescue] - Restore the nextcloud instance."
  command: "mv {{ nextcloud_webroot_old }} {{ nextcloud_webroot }}"
  args:
    creates: "{{ nextcloud_webroot }}/version.php"

- name: "[NC-Rescue] - Nextcloud is not in maintenance mode."
  become_user: "{{ nextcloud_websrv_user }}"
  command: php occ maintenance:mode --off
  args:
    chdir: "{{ nextcloud_webroot }}"
